import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? 'https://trytendr.org'),
  title: 'Tendr — AI Home Assistant Platform',
  description:
    'Give your homeowners an AI home assistant delivered entirely over SMS. Proactive maintenance reminders, instant warranty answers, and conversational onboarding — no app required.',
  openGraph: {
    title: 'Tendr — AI Home Assistant Platform',
    description:
      'Give your homeowners an AI home assistant delivered entirely over SMS. No app required.',
    type: 'website',
    // OG image is generated by app/opengraph-image.tsx via Next.js ImageResponse
  },
  other: {
    'impact-site-verification': '73a2c675-91d2-4d59-8123-5d237c941dfa',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
