const steps = [
  {
    number: '01',
    title: 'Connect your homeowners',
    description:
      'Register homeowners via a simple webhook API or bulk CSV import. Each one is automatically tied to your company code, your warranty plan, and your dedicated phone number.',
    detail: 'Supports thousands of users at import time with rate-limited background processing.',
  },
  {
    number: '02',
    title: 'Tend handles onboarding',
    description:
      'Our AI texts each homeowner and gathers their complete home profile through natural conversation — roof type, HVAC units, plumbing, appliances, pool details, and more.',
    detail: 'Property data is auto-populated from ATTOM when available, so homeowners are never asked what the system already knows.',
  },
  {
    number: '03',
    title: 'Automated value, forever',
    description:
      'Tend sends personalized maintenance reminders, answers warranty questions grounded in your actual policy documents, and helps homeowners open claims — all automatically, over SMS.',
    detail: "Every message is generated by AI and personalized to the homeowner's specific home, not sent from a generic template.",
  },
]

function CheckIcon() {
  return (
    <svg
      className="w-5 h-5 text-brand-600 shrink-0"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      aria-hidden="true"
    >
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
    </svg>
  )
}

export default function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="bg-slate-50 py-20 lg:py-28"
      aria-labelledby="how-it-works-heading"
    >
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <p className="text-sm font-semibold text-brand-600 uppercase tracking-wider mb-3">
            How it works
          </p>
          <h2
            id="how-it-works-heading"
            className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight text-balance"
          >
            From sign-up to fully automated in three steps
          </h2>
          <p className="mt-4 text-lg text-slate-600">
            Tend integrates with your existing platform and takes over the ongoing homeowner
            relationship — so your team doesn&apos;t have to.
          </p>
        </div>

        {/* Steps */}
        <div className="relative">
          {/* Connector line (desktop) */}
          <div
            className="hidden lg:block absolute top-12 left-[calc(16.67%-1px)] right-[calc(16.67%-1px)] h-0.5 bg-brand-100"
            aria-hidden="true"
          />

          <div className="grid lg:grid-cols-3 gap-8 lg:gap-12">
            {steps.map((step) => (
              <div key={step.number} className="relative">
                {/* Step number bubble */}
                <div className="flex lg:justify-center mb-6">
                  <div className="relative flex items-center justify-center w-12 h-12 rounded-full bg-brand-600 text-white text-lg font-extrabold shadow-lg shadow-brand-600/30 ring-4 ring-white z-10">
                    {step.number}
                  </div>
                </div>

                <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
                  <h3 className="text-lg font-bold text-slate-900 mb-2">{step.title}</h3>
                  <p className="text-slate-600 text-sm leading-relaxed mb-4">{step.description}</p>
                  <div className="flex items-start gap-2 pt-3 border-t border-slate-100">
                    <CheckIcon />
                    <p className="text-xs text-slate-500 leading-relaxed">{step.detail}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
