-- Part 1: Add monitoring columns to conversations table
ALTER TABLE public.conversations
  ADD COLUMN ai_quality_flag     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN ai_quality_reason   TEXT,
  ADD COLUMN manually_reviewed   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN manually_flagged    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN manually_flagged_reason TEXT;

COMMENT ON COLUMN public.conversations.ai_quality_flag IS
  'Set to true by the nightly quality review job when Claude finds issues in this conversation.';
COMMENT ON COLUMN public.conversations.ai_quality_reason IS
  'Semicolon-joined summary of issues found by the nightly AI quality review.';
COMMENT ON COLUMN public.conversations.manually_reviewed IS
  'Set to true by an admin after reviewing the conversation thread.';
COMMENT ON COLUMN public.conversations.manually_flagged IS
  'Set to true by an admin who manually flags the conversation for attention.';
COMMENT ON COLUMN public.conversations.manually_flagged_reason IS
  'Admin-provided reason for the manual flag.';

-- Add monitoring columns to users table
ALTER TABLE public.users
  ADD COLUMN onboarding_gaps       TEXT[],
  ADD COLUMN onboarding_gap_flagged BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.users.onboarding_gaps IS
  'Array of home_details field names that were null without a documented "I don''t know" response after onboarding completed.';
COMMENT ON COLUMN public.users.onboarding_gap_flagged IS
  'Set to true when at least one gap was detected during the onboarding completeness check.';

-- Create system_alerts table
CREATE TABLE public.system_alerts (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type  TEXT        NOT NULL,
  user_id     UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  description TEXT        NOT NULL,
  resolved    BOOLEAN     NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.system_alerts IS
  'Critical failure alerts generated by the monitoring system (API failures, delivery failures, onboarding issues, etc.).';
COMMENT ON COLUMN public.system_alerts.alert_type IS
  'Category of the alert: "api_failure", "delivery_failure", "onboarding_stuck", "no_ai_response", "reminder_failure", etc.';

CREATE INDEX system_alerts_resolved_created_at_idx ON public.system_alerts (resolved, created_at DESC);
CREATE INDEX system_alerts_user_id_idx             ON public.system_alerts (user_id);

-- RLS: only service role (server-side) writes; portal members can read their tenant's alerts
ALTER TABLE public.system_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "system_alerts: tenant members can select"
  ON public.system_alerts FOR SELECT
  USING (
    user_id IS NULL
    OR user_id IN (
      SELECT id FROM public.users WHERE tenant_id IN (
        SELECT tenant_id FROM public.tenant_users WHERE auth_user_id = auth.uid()
      )
    )
  );

-- Service role (used by admin routes and cron) bypasses RLS; no additional policy needed for INSERT/UPDATE.
